# spring.application.name=news-subscriber-mono-demo
server: 8080
spring:
  application:
    name: news-subscriber-mono-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dbtest
#    username: sa
#    password: sa
  h2:
    console: # Web 控制台配置
      enable: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update # 如果表不存在则创建，表存在则更新
    show-sql: true # 启用 sql 日志输出
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql